### ISSUE TITLE
Game Engine Grammar Modification

### ISSUE THREAD

**Issue by serotoninpm** [princeton-nlp/XTX#1]
I am impressed with your research. Thanks for the good research.

I have one question.

In your research, you use the jericho library with modified grammar.

1) What were the shortcomings of the original library?
2) What did you improve in the new library and how?

I would really appreciate it if you could answer!

**Comment by jens321** [comment]
Hi! Thanks for checking out our repo! 

The only modification we made was that we added walkthrough actions at some states for certain games where the correct action was not given by the [valid actions handicap provided by jericho](https://jericho-py.readthedocs.io/en/latest/tutorial_quick.html#getting-valid-actions). The reason we did this is that it's otherwise impossible for agents to make progress at these states. 

Hope that helps!

**Comment by serotoninpm** [comment]
Thank you for your kind response.

I will support your wonderful research!
